/* This file better be generated by configure script. */
#ifndef _KLPMAKE_CONFIG_H
#define _KLPMAKE_CONFIG_H
/*
 * OSes might have different directories. This is of openEuler.
 * It seems that we need some configure scripts.
 */
#include <libdwarf-0/dwarf.h>
#include <libdwarf-0/libdwarf.h>
// Debian
//#include <libdwarf/dwarf.h>
//#include <libdwarf/libdwarf.h>
#include <clang-c/Index.h>

#endif
