#!/bin/bash
#
# KLPMAKE helpers.
#
# Copyright (c) 2023 ISCAS     laokz <zhangkai@iscas.ac.cn>
# KLPMAKE is licensed under Mulan PSL v2.
# You can use this software according to the terms and conditions of
# the Mulan PSL v2. You may obtain a copy of Mulan PSL v2 at:
#          http://license.coscl.org.cn/MulanPSL2
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES
# OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
# TO NON-INFRINGEMENT, MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
# See the Mulan PSL v2 for more details.

function kaslr_offset()
{
	local -i k v
	k="0x"$(grep -E "\<_text\>" /proc/kallsyms|cut -d' ' -f1)
	v="0x"$(readelf -s $VMLINUX|grep -E "\<_text\>"|cut -d' ' -f2)
	echo $((k-v))
}
